/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoaula;

/**
 *
 * @author daniel
 */
public class TorneoDeFutbol extends javax.swing.JFrame {

    /**
     * Creates new form TorneoDeFutbol
     */
    public TorneoDeFutbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPrincipal = new javax.swing.JPanel();
        ImagePanel = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();
        Tittle = new javax.swing.JPanel();
        TittleLetter = new javax.swing.JLabel();
        SingIn = new javax.swing.JLabel();
        LogoUPC = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Career = new javax.swing.JTextField();
        TeamSoccer = new javax.swing.JTextField();
        NameSeparator = new javax.swing.JSeparator();
        LastNameSeparator = new javax.swing.JSeparator();
        CareerSeparator = new javax.swing.JSeparator();
        TeamSoccerSeparator = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        fondoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagePanel.setBackground(new java.awt.Color(0, 102, 0));

        Image.setForeground(new java.awt.Color(0, 0, 0));
        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image.setText("imagen");

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoPrincipal.add(ImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 250, 500));

        Tittle.setBackground(new java.awt.Color(255, 255, 255));

        TittleLetter.setBackground(new java.awt.Color(255, 255, 255));
        TittleLetter.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TittleLetter.setForeground(new java.awt.Color(0, 0, 0));
        TittleLetter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleLetter.setText("TORNEO DE FUTBOL UPC AGUACHICA");

        javax.swing.GroupLayout TittleLayout = new javax.swing.GroupLayout(Tittle);
        Tittle.setLayout(TittleLayout);
        TittleLayout.setHorizontalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TittleLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TittleLayout.setVerticalGroup(
            TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TittleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TittleLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoPrincipal.add(Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 70));

        SingIn.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        SingIn.setForeground(new java.awt.Color(0, 0, 0));
        SingIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SingIn.setText("REGISTRARSE");
        fondoPrincipal.add(SingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 50));

        LogoUPC.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LogoUPC.setForeground(new java.awt.Color(0, 0, 0));
        LogoUPC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoUPC.setText("LOGO UPC");
        fondoPrincipal.add(LogoUPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, 50));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 153, 153));
        Name.setText("Nombre");
        Name.setBorder(null);
        fondoPrincipal.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, 30));

        LastName.setBackground(new java.awt.Color(255, 255, 255));
        LastName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(153, 153, 153));
        LastName.setText("Apellido");
        LastName.setBorder(null);
        fondoPrincipal.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 220, 30));

        Career.setBackground(new java.awt.Color(255, 255, 255));
        Career.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Career.setForeground(new java.awt.Color(153, 153, 153));
        Career.setText("Carrera");
        Career.setBorder(null);
        fondoPrincipal.add(Career, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 220, 30));

        TeamSoccer.setBackground(new java.awt.Color(255, 255, 255));
        TeamSoccer.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TeamSoccer.setForeground(new java.awt.Color(153, 153, 153));
        TeamSoccer.setText("Equipo");
        TeamSoccer.setBorder(null);
        fondoPrincipal.add(TeamSoccer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 220, 30));
        fondoPrincipal.add(NameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 220, -1));
        fondoPrincipal.add(LastNameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, -1));
        fondoPrincipal.add(CareerSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, -1));
        fondoPrincipal.add(TeamSoccerSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 220, -1));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("ENTRAR");
        jTextField1.setToolTipText("");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        fondoPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 120, 30));

        getContentPane().add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TorneoDeFutbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TorneoDeFutbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TorneoDeFutbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TorneoDeFutbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TorneoDeFutbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Career;
    private javax.swing.JSeparator CareerSeparator;
    private javax.swing.JLabel Image;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JTextField LastName;
    private javax.swing.JSeparator LastNameSeparator;
    private javax.swing.JLabel LogoUPC;
    private javax.swing.JTextField Name;
    private javax.swing.JSeparator NameSeparator;
    private javax.swing.JLabel SingIn;
    private javax.swing.JTextField TeamSoccer;
    private javax.swing.JSeparator TeamSoccerSeparator;
    private javax.swing.JPanel Tittle;
    private javax.swing.JLabel TittleLetter;
    private javax.swing.JPanel fondoPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
